### ISSUE TITLE
Bug: SmallRyeConfig#getValues: mapFactory is not used

### ISSUE THREAD

**Issue by magicprinc** [smallrye/smallrye-config#1096]
`io.smallrye.config.SmallRyeConfig#getValues(java.lang.String, org.eclipse.microprofile.config.spi.Converter<K>, org.eclipse.microprofile.config.spi.Converter<V>, java.util.function.IntFunction<java.util.Map<K,V>>)`

```java
public <K, V> Map<K, V> getValues(
    String name,
    Converter<K> keyConverter,
    Converter<V> valueConverter,
    IntFunction<Map<K, V>> mapFactory // 1️⃣ any Map could be created
){
  try {
    // 2️⃣ but in most cases caller will receive HashMap (with optional ClassCastException)
    return getValue(name, newMapConverter(keyConverter, valueConverter));
  } catch (NoSuchElementException e) {
    Map<String, String> mapKeys = getMapKeys(name);
    if (mapKeys.isEmpty()) {
        throw new NoSuchElementException(ConfigMessages.msg.propertyNotFound(name));
    }
    // 3️⃣ only this branch creates required type of Map
    Map<K, V> map = mapFactory.apply(mapKeys.size());
    for (Map.Entry<String, String> entry : mapKeys.entrySet()){
       map.put(convertValue(ConfigValue.builder().withName(entry.getKey()).withValue(entry.getKey()).build(),
                keyConverter), getValue(entry.getValue(), valueConverter));
    }
```

**Comment by dmlloyd** [comment]
I agree that this is inconsistent. We should have a variation of `newMapConverter` which accepts a map factory, using `HashMap::new` as the default.

As an aside, this way of doing map conversion is pretty weird: it first tries to convert a single key to a map and then tries to read multiple keys as a map. I don't like the double-duty because the user will already know what they want, and I doubt very much that the thing that they want for any given property is both behaviors.

**Comment by radcortez** [comment]
Before we added support to `Map` with the key in the property name, we accepted an inline value to create the `Map` as `key=value;another-key=value`. A similar thing happened with `Collection` values, where MP Config defines commas to separate values, and we added the indexed format as `[x].`

We ended up proving double-duty methods because when we are creating the `Config,` we never know which format is being used, so we need to try both. Of course, if the user is calling these methods directly, we could force to use the single responsibility APIs. Ideally, we should deprecate and later remove the inline value version for both `Collection` and `Map`. We could easily do that for the `Map` part, but for `Collections` it would be harder without going against the spec.

**Comment by magicprinc** [comment]
I like inline collections and Maps.
BTW, this is the only way for ConfigProperty.defaultValue to handle them.
So please, don't remove 🙏

But my bug report is not about it, but about the created Map class.
E.g. I need LinkedHashMap, but SRC creates HashMap and I receive ClassCastException

The first sentence in @dmlloyd comment is an exact match.

**Comment by dmlloyd** [comment]
I don't think there is any reason to get rid of inline maps, and definitely no reason to get rid of inline collections. But I don't think it makes a lot of sense to try one and fall back to the other.

**Comment by magicprinc** [comment]
Vert.x Config is an interesting step in this direction (and they have a lot of extensions to read configuration from everywhere).
Quarkus potentially has two mature configuration systems out-of-the box.
The main problem of Vert.x Config is: you need Vert.x to run it. I.e. one vert.x to read configs and the second - main - to start with them.

BTW, the main goal of this bug report is to fix the type of the Map: use factory
