### ISSUE TITLE
Cannot use (reference) ConfigurationProperties field in another ConfigurationProperties

### ISSUE THREAD

**Issue by roman-kitko** [smallrye/smallrye-config#1126]
When we reference @ConfigProperties class from another  one (like nesting properties), it does not work.
It works with @ConfigMapping and interfaces, but that forces us to use smallrye-config api instead of micoprofile config classes through whole project.

@ConfigProperties(prefix = "databaseProperties")
public class DatabasePropertiesClass {
    @ConfigProperties(prefix = "hostProperties")
    private HostPropertiesClass hostProperties;
    private int connections;
}

@ConfigProperties(prefix = "hostProperties")
public class HostPropertiesClass {
    private String host;
    private int port;
    private String url;
}

SmallRyeConfigBuilder configBuilder = (SmallRyeConfigBuilder) ConfigProviderResolver.instance().getBuilder();
configBuilder.withMapping(HostPropertiesClass.class, "hostProperties");
configBuilder.withMapping(DatabasePropertiesClass.class, "databaseProperties");
configBuilder.build()

io.smallrye.config.ConfigValidationException: Configuration validation failed:
	java.lang.IllegalArgumentException: SRCFG00013: No Converter registered for class org.vpda.common.config.HostPropertiesClass

	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:75)
	at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:84)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:714)

The problem is, for ConfigProperties new ConfigMapping interface is generated, but this operation is stateless.
Here : io.smallrye.config.ConfigMappingGenerator#generate(java.lang.Class<?>, java.lang.String)

For field "HostPropertiesClass hostProperties", the method with return type HostPropertiesClass is generated, but here it should use already generated interfaces. 

ConfigMappingGenerator while generating interfaces, must consider already generated interfaces.

Sample properties to use

databaseProperties.hostProperties.host=DB
databaseProperties.hostProperties.port=88
databaseProperties.hostProperties.url=myUrl
databaseProperties.connections=66

**Comment by roman-kitko** [comment]
3.6.0 version used at issie

**Comment by roman-kitko** [comment]
3.6.0 version used

**Comment by radcortez** [comment]
The MP Config specification does not define nested elements in `@ConfigProperties`, APIs, or paths required to support such a feature. We did the work for `@ConfigMapping`, and that was our proposal to the MP Config group, which unfortunately decided to go another route.

We acknowledged that we only implemented the bare minimum to comply with the `@ConfigProperties` specification and pass the TCK, since supporting both `@ConfigProperties` and `@ConfigMapping` is quite time-consuming. We believe an interface-based approach is a better solution for the Config space, so we invested most of our time in `@ConfigMapping.` The Jakarta Config group will also adopt interface-based configuration: https://github.com/jakartaee/config/discussions/122.

When users hit some more advanced usage of `@ConfigProperties,` we recommend moving to `@ConfigMapping` instead. We understand that our API is out of the specification, but it is as stable as the MP Config API.

We are happy to review any PRs that improve the `@ConfigProperties` support. However, considering that MP Config will be replaced with Jakarta Config and that MP Config is mostly stale, we prefer to put our effort into something other than this area.

**Comment by roman-kitko** [comment]
Ok, thx for verbose reply.
I understand your approach. It is really pity, such useful feature is out of scope of specification.

Closing the issue, thx for help.
