### ISSUE TITLE
(Possibly not an issue) - Optional collections

### ISSUE THREAD

**Issue by bobmcwhirter** [smallrye/smallrye-config#15]
Thorntail v4 supported, possibly against the spec, injectables such as

    Optional<List<Thing>>

SR doesn't, but happily treats a non-present value as an empty collection instead of throwing a `NoSuchElement` or whatnot, which is good.

I was wondering, how do we read the spec, in terms of `Optional` plus collections?  Is it useful to differentiate between an empty collection and a not-present `Optional` collection if no config values are specified at all?

e.g., from a properties POV:

collection with data

    foo.bar: 1,2

empty collection

    foo.bar:

null, `!optional.isPresent` collection

    # no foo.bar key

**Comment by jmesnil** [comment]
I've opened https://github.com/eclipse/microprofile-config/issues/376 to discuss some of these use cases and clarify the behaviour in the spec.

**Comment by dmlloyd** [comment]
If my empty values proposal is accepted then it has implications for this because returning an empty `List` would not be supported by itself.  We'd either have to specify explicitly that `List` (and other naturally-emptiable types like `String`) cannot return empty values, or specify that in the absence of `Optional`, these types' "natural" empty representation be used instead.  But one consequence would be that if your field type is `Optional<List<X>>`, you'll never get a "present" optional containing an empty list.

**Comment by dmlloyd** [comment]
This is sorted out in 1.5.0 and later.  A `List<X>` cannot be empty; an `Optional<List<X>>` can be an empty optional or a non-empty `List`.
