### ISSUE TITLE
Split module with smallrye-config-common

### ISSUE THREAD

**Issue by acoburn** [smallrye/smallrye-config#191]
The 1.4.x series introduced a `smallrye-config-common` artifact that contains code that is shared across multiple provider implementations. The problem is that this module (jar) exports classes from the same package namespace as several other modules.

Specifically:
smallrye-common-config exports:
`io.smallrye.config`
`io.smallrye.config.utils`

smallrye-config exports:
`io.smallrye.config`
`io.smallrye.config.inject`

the filesystem source exports:
`io.smallrye.config`

And both the zk and hocon sources export:
`io.smallrye.configsource`

In a normal JavaSE/classpath context it isn't strictly a problem to have multiple jars exposing classes from the same namespace, but this does become very problematic in a Java11+ (module-path) or OSGi context where package boundaries cannot overlap with jar boundaries.

Would it be possible to place all of the `smallrye-config-common` classes into `io.smallrye.config.util`? And would it be possible to assign the various config source implementations (file, zk, hocon) to their own package namespace? Doing so will make it possible to use these components in a modular environment. (For example, the 1.3.x series works fine with the Java11 modularity, but 1.4.x doesn't)

**Comment by kenfinnigan** [comment]
Apologies for that, it certainly wasn't intentional.

Here's a proposal for packages:

smallrye-common-config:
`io.smallrye.config.common`
`io.smallrye.config.common.utils`

smallrye-config:
`io.smallrye.config`
`io.smallrye.config.inject`

filesystem config source:
`io.smallrye.config.source.file`

zookeeper config source:
`io.smallrye.config.source.zookeeper`

hocon config source:
`io.smallrye.config.source.hocon`

JSON converter:
`io.smallrye.config.converter.json` [No change]

cdi provider:
`io.smallrye.config.util.injection`

events:
`io.smallrye.config.events` [No Change]

Thoughts?

This would also require us to bump to 1.5.x for a version as well

@dmlloyd and @phillip-kruger please comment as well.

**Comment by acoburn** [comment]
Thanks @kenfinnigan. Your proposal sounds great from my perspective.

**Comment by dmlloyd** [comment]
It looks good to me.

**Comment by dmlloyd** [comment]
I'll do these refactors.  If someone else has already started though, please let me know ASAP.

**Comment by kenfinnigan** [comment]
I hadn't gotten to it yet, so by all means go ahead

**Comment by acoburn** [comment]
Thanks for making this change. I can confirm that the new package structure works well in a Java11 module context.
