### ISSUE TITLE
Overwriting Collection Converter not possible / Collections should never be NULL

### ISSUE THREAD

**Issue by svenhaag** [smallrye/smallrye-config#211]
Hi,

I'm using SmallRye Config 1.5 and my aim is to NEVER EVER return `null` for any Collection. For me this is a bug in the current implementation.

However, according to the spec it should be possible to [overwrite any converter with a custom converter](https://github.com/eclipse/microprofile-config/blob/1.3/spec/src/main/asciidoc/converters.asciidoc#adding-custom-converters).
I was not able to do so for the [CollectionConverter](https://github.com/smallrye/smallrye-config/blob/7111a2ba1d3dcc0b61021b26df1c123a4be52bc6/implementation/src/main/java/io/smallrye/config/Converters.java#L614).

So I think the actual "bug" is located in these 2 positions, where `null` is returned:
https://github.com/smallrye/smallrye-config/blob/7111a2ba1d3dcc0b61021b26df1c123a4be52bc6/implementation/src/main/java/io/smallrye/config/Converters.java#L631
and
https://github.com/smallrye/smallrye-config/blob/7111a2ba1d3dcc0b61021b26df1c123a4be52bc6/implementation/src/main/java/io/smallrye/config/Converters.java#L643

Any advice or (bug-)fix is very much appreciated.

**Comment by dmlloyd** [comment]
There are two points where the API is concerned with empty values, and then CDI adds a third layer of consideration.

The first point is in the `Converter` interface itself.  This interface is using `null` to represent "empty", and that is as it should be.  There is no other value that works for every possible data type that can do the job, so `null` is it.

The second point is in the `Config` interface (specifically the `getValue` method and friends).  At this point, it *should* be impossible to get a `null` back.  If a converter returns `null` indicating empty, then you will get a `NoSuchElementException` except for a few special cases (`Optional<X>`, `OptionalInt`, `OptionalLong`, and `OptionalDouble`) which are managed by special converters.  So in this way, you should never see the `null` value from the converter instance unless you bypass the whole API.

The third point (CDI injection) is a bit more murky.  Historically it has allowed `null` values in certain situations, and in fact was generally very unclear about when and how such values can be returned.  In the latest upstream code (post-#209) however, this should be fixed so that `null` never occurs, and `Optional` is required when an empty collection, array, or other value is returned.  If you could test your case to verify that assertion, it would be most appreciated.

**Comment by svenhaag** [comment]
Hi, thanks for the insight. Indeed I have written a simple JUnit test for this. Please see:

```
    @Inject
    @ConfigProperty(name = "test.converter.stringList", defaultValue = "")
    private Provider<List<String>> listWithEmptyDefault;

    @Test
    void listWithEmptyDefaultShouldNeverBeNull() {
        assertNotNull(listWithEmptyDefault.get()); // FAILS
    }
```
Is that sufficient?

Cheers

**Comment by dmlloyd** [comment]
Perfect, thanks. I'll see if I can figure out what is going wrong.

**Comment by svenhaag** [comment]
Thanks for such a quick fix, i will test tomorrow. However this does not fix the issue that overwriting every converter schould be possible.

**Comment by dmlloyd** [comment]
Yeah, I agree.  When it comes to collection converters, #162 is closely related, as is #40.  I think that supporting parameterized converters is going to be something we'll want to do, though it might be fairly tricky.

**Comment by svenhaag** [comment]
Great! So in turn this means that this isnt checked from the TCK obviously?

**Comment by dmlloyd** [comment]
Right, the TCK has a lot of holes unfortunately.
