### ISSUE TITLE
Expansion broken with 1.8.0

### ISSUE THREAD

**Issue by cescoffier** [smallrye/smallrye-config#309]
I have a configuration property using the following value:
```
file:target/prices/?fileName=${date:now:yyyyMMddssSS}.txt&charset=utf-8
```

This syntax comes from Apache Camel and indicates to Camel that the file name must use a timestamp. 

In 1.7.0 it behaves correctly, and Camel gets the right value. However, with 1.8.0, it gets:

```
file:target/prices/?fileName=now:yyyyMMddssSS.txt&charset=utf-8
```

The `${}` are missing which confuses Camel. As a result, it now creates a file names `now:yyyyMMddssSS.txt`.

**Comment by dmlloyd** [comment]
You'll have to escape that `$` with a `\`.

**Comment by cescoffier** [comment]
Hum... not sure it's a good solution. It would make the configuration of camel routes quite convoluted.

**Comment by radcortez** [comment]
This is because we now have expansion on by default in Smalrye Config, which seems to clash with Camel.

We could turn it off again, but this most likely will be a feature of MP Config API, so the issue will reappear.

We do have a way to turn of expansion if required. We can either use the API
`io.smallrye.config.Expressions#withoutExpansion(java.lang.Runnable)`, to pass in the calling code that doesn't want to use Expansion (like we have on Quarkus). Or create a `SmallRyeConfigFactory` to construct the Config object with expansion off.

Would that work for you @cescoffier ?

**Comment by cescoffier** [comment]
I need to check, but yes, it may work for me.

It needs to be very carefully documented, as I don't believe it's only
going to break Camel, but a lot of other things too. I will document it on
Reactive Messaging, but you should document it in SmallRye (and highlight
it).

Le lun. 11 mai 2020 à 14:27, Roberto Cortez <notifications@github.com> a
écrit :

**Comment by radcortez** [comment]
Thanks. Let men know if you need any help.

I'll write some documentation around this.

**Comment by cescoffier** [comment]
Even with escaping it does not seem to work:

```
file:target/prices/?fileName=\${date:now:yyyyMMddssSS}.txt&charset=utf-8
```

Is read as: `$, now:yyyyMMddssSS.txt`

**Comment by cescoffier** [comment]
Found a way:
```
file:target/prices/?fileName=\$${date:now:yyyyMMddssSS}.txt&charset=utf-8"
```

Please tell me it's not the expected behavior?

**Comment by radcortez** [comment]
Just the double dollar should work.

But the issue is that we don't have the escape codes on by default:
https://github.com/smallrye/smallrye-common/blob/0b59733491ff936808cd26a4b300f11fe3f2a5f0/expression/src/main/java/io/smallrye/common/expression/Expression.java#L687

https://github.com/smallrye/smallrye-config/blob/c0a1a95f5cfc31b937a1135a1478960960b8aa9b/implementation/src/main/java/io/smallrye/config/ExpressionConfigSourceInterceptor.java#L37

I'll add it by default.

**Comment by radcortez** [comment]
@cescoffier I can't turn on escape by default, because it is going to break other stuff. Double escaping is removed when a variable is expanded to its plain string. An issue, is that if we escape a comma, then we may have unexpected results in array config parsing.

I did add a test case in https://github.com/smallrye/smallrye-config/issues/309 and double `$$` should do the trick. You shouldn't need to write `\$`.

**Comment by cescoffier** [comment]
I confirm that `$$` works. 

Can you confirm that it only affects configuration using `${ ...}` and not properties containing `$` (not followed by a `{`. If the latter is true, it is going to break a lot on things such as Mongo DB URL, database query statement...

**Comment by radcortez** [comment]
Yes, properties with a single `$` and no `{}` are not expanded and keep their original value.

But if you use a double `$$`, then you only get one `$` in the resolved value (like you have with you camel route).

**Comment by radcortez** [comment]
BTW, we do use the same expansion resolution code that is used in Quarkus.

**Comment by cescoffier** [comment]
@radcortez thanks for the clarification. 

So at the moment, I don't use Camel routes in Quarkus. However, I believe it's already used by Quarkus Camel. In addition, we got requests to support the Camel connector in Quarkus - so soon it will be used (with some definition of "soon" :-))

**Comment by cescoffier** [comment]
Closing this issue after clarification.

**Comment by radcortez** [comment]
Sure :)

Let me know if I can help with anything else.
