### ISSUE TITLE
what should Config.getOptionalValue("missing.key", OptionalInt.class) return?

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-config#376]
I was just trying to use `OptionalInt` in Quarkus and got myself sidetracked into how Quarkus validates configuration values presence. There, I found that with SmallRye Config, the following call

```java
Config.getOptionalValue("missing.key", OptionalInt.class)
```

returns a non-empty `Optional`, whose value is an empty `OptionalInt`.

It kinda sorta makes sense, but then returning an empty `Optional` would also make sense. I guess there are probably arguments for both options.

WDYT?

**Comment by radcortez** [comment]
I guess we could flatten the Optionals, but in that case it also means that we would need to box the primitive Optional types to the generic one. 

There are probably a few other corner cases around this. Let me have a look.

**Comment by dmlloyd** [comment]
There's really no way to make it behave consistently.  I doubt there's a good solution; a non-good solution would be to manually compare the class to see if it is one of the `Optional*` types, but that's really inelegant considering that the user should be using `getValue` for any property value that they don't want wrapped in `Optional<T>`.

**Comment by Ladicek** [comment]
Is there a good way to find out if some key has a value? Because I see Quarkus using `Config.getOptionalValue(...).isPresent()` for that purpose (https://github.com/quarkusio/quarkus/blob/666b045a5d/extensions/arc/runtime/src/main/java/io/quarkus/arc/runtime/ConfigRecorder.java#L35). I guess the best way is probably `getOptionalValue(key, String.class)`, that is, without attempting conversion, but I can see why Quarkus wants to convert to the target type during validation.

**Comment by dmlloyd** [comment]
In every case that Quarkus cares about, the value should already have been validated.  But generally I'd say that it's hard to do without special knowledge of the type.  Converters always have the ability to provide special converted representations for empty values (such as `OptionalInt.empty()` or even possibly e.g. empty `List` or other collections for example), and furthermore converters have the ability to accept multiple representations that yield empty values (for example the standard `List` converter will return an empty list for the input string `,`).

So if you're trying to generically determine whether a property is present in some absolute sense, you're barking up the wrong tree.  If a configuration property is required, just use `getValue()` which throws an exception if a required value is not present, or `getOptionalValue()` which returns an empty value.  If the converter never returns an empty value, then the requirement should be considered to be always satisfied, end of story.  This is why all of our configuration systems represent optionality by way of `Optional<T>` or `Optional*` types: because converters for those types are always satisfied.

**Comment by Ladicek** [comment]
> if you're trying to generically determine whether a property is present in some absolute sense, you're barking up the wrong tree

I'm not, Quarkus is, in the method I linked above. But it excludes `Optional` types from this validation, and your explanation helps me understand why, so thanks for that :-)

**Comment by radcortez** [comment]
If you really want the value without the conversion, you can call `io.smallrye.config.SmallRyeConfig#getRawValue` or `io.smallrye.config.SmallRyeConfig#getConfigValue`.

The `ConfigValue` is a config accessor in essence. We already support this, but it will also be available in MP Config 2.0.

**Comment by dmlloyd** [comment]
> > if you're trying to generically determine whether a property is present in some absolute sense, you're barking up the wrong tree
> 
> I'm not, Quarkus is, in the method I linked above. But it excludes `Optional` types from this validation, and your explanation helps me understand why, so thanks for that :-)

No problem.  The code you referenced, by the way, is simply incorrect, so don't use it as a reference for the right way to do things!
