### ISSUE TITLE
An Injected Config instance should be serializable

### ISSUE THREAD

**Issue by tevans78** [smallrye/smallrye-config#405]
The MP Config spec requires that an injected Config instance must be serializable.
https://github.com/eclipse/microprofile-config/issues/89

If a non-serializable ConfigSource is added to a SmallRye Config then it is no longer serializable and it fails the TCK test.
https://github.com/eclipse/microprofile-config/blob/2c42cc9f86112aef975ee5e06e90aef1dd6379df/tck/src/main/java/org/eclipse/microprofile/config/tck/ConfigProviderTest.java#L146

The Open Liberty implementation "solved" this by always injecting a serializable proxy instance instead of the real Config. I don't particularly like this solution either but putting it here for reference;
https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.microprofile.config.1.1.cdi/src/com/ibm/ws/microprofile/config/cdi/DelegatingConfig.java

**Comment by radcortez** [comment]
Not sure if we should follow the same approach.

All of our provider Sources are already `Serializable`. Yes, it is a burden for the user to add the `Serializable`, but on the other hand, this is not needed most of the times.

I wonder if we should clarify in the spec if Sources should also be `Serializable`. We do need them right now because of the TCK, but usually only `Config` is require due to injection in session scoped beans.

**Comment by Emily-Jiang** [comment]
@radcortez I think if the implementation can ensure the config object seralizable even if some config source has not implemented `Serializable`, it will be best. Even if we add a requirement in the spec to ask all of the config source to implement `Serializable`, this is not user friendly and end users will forget doing it.

**Comment by radcortez** [comment]
We don't really need to ask the user to implement `Serializable`. We can just add it to `ConfigSource`. For instance `Converter` extends `Serializable`.

**Comment by Azquelt** [comment]
If you add `Serializable` to `ConfigSource`, you're asking any config source author to ensure that their config source can be safely serialized and deserialized. There are enough serialization pitfalls that I wouldn't want to do that unless the benefit of doing so is worth it.

It would be fairly easy to have a different serializable config used for injection which just looks up the config on first use and delegates to it. It wouldn't have to serialize any state since it can just repeat the lookup when it's deserialized. I can make a PR for this.
