### ISSUE TITLE
Duplicate microprofile-config.properties ConfigSoucres from Config.getConfigSources()

### ISSUE THREAD

**Issue by Joseph-Cass** [smallrye/smallrye-config#522]
For example:
```
Config config = ConfigProvider.getConfig();
System.out.println("Default ConfigSources: "+config.getConfigSources());
```

Produces (split across new lines for readability):
```
Default ConfigSources: [
SysPropConfigSource, 
EnvConfigSource, 
PropertiesConfigSource[source=file:/<path>/META-INF/microprofile-config.properties], 
PropertiesConfigSource[source=file:/<path>/META-INF/microprofile-config.properties], 
DefaultValuesConfigSource
]
```

These 2 microprofile-config.properties ConfigSources contain the same properties (from `.getProperties()`) but are not equal (from `.equals()`)  

The same thing also happens for `microprofile-config-<profile_name>.properties` for Config Profiles on the [Config Source level](https://download.eclipse.org/microprofile/microprofile-config-2.0/microprofile-config-spec-2.0.html#_on_config_source_level).

**Comment by radcortez** [comment]
@Joseph-Cass are you able to provide a reproducer? I've added one in #523 but it seems fine.

**Comment by radcortez** [comment]
Sure.

**Comment by tevans78** [comment]
I tested this too and got the same result as Joe. I think it is because when you search for "META-INF/microprofile-config.properties", you will find resources _anywhere_ on the classpath, including those that are inside "WEB-INF/classes" (which is on the classpath).

i.e. searching the classpath for resources called `META-INF/microprofile-config.properties`
will find both
`/META-INF/microprofile-config.properties`
AND
`/WEB-INF/classes/META-INF/microprofile-config.properties`

However, I modified your new test to use `/WEB-INF/classes/META-INF/microprofile-config.properties` and it still passed. I don't know what the difference between OpenLiberty the SmallRye test environment is.

**Comment by tevans78** [comment]
Is it that "WEB-INF/classes" is only on the classpath in a JavaEE environment? The SmallRye test isn't really running inside an JavaEE container?

**Comment by tevans78** [comment]
Pretty sure that https://github.com/smallrye/smallrye-config/blob/aaa12d58083b48c6ec3ef03c4bc31ff4e603ab1e/implementation/src/main/java/io/smallrye/config/SmallRyeConfigBuilder.java#L147 should be removed. It is up to the classloader to decide what is on the classpath. The SmallRye code should not need to worry about it. I will create a PR ... will also need to fix up the unit tests so that they don't use WEB-INF/classes.

**Comment by radcortez** [comment]
Well a WebApplication classloader must make everything available in `/WEB-INF/classes/`. The lookup from a web application perspective to `/WEB-INF/classes/META-INF/microprofile-config.properties` does not make sense, because the actual classpath resource is `META-INF/microprofile-config.properties`, so it shouldn't return any results and probably explains why we didn't see this behaviour until now.

I'm wondering if OpenLiberty webapp classloader is looking up in both places, and then giving duplicate results.

Do you have an OpenLiberty test / sample that I can look at?
