### ISSUE TITLE
Make Converters more flexible

### ISSUE THREAD

**Issue by hrstoyanov** [smallrye/smallrye-config#569]
Consider this converter of strings to enums:
```
 enum DatabaseType {

        mssql, oracle, postgres, mysql;

        public interface Parser extends Converter<DatabaseType> {
            @Override
            default ProxyConfig.DatabaseType convert(final String value) {
                return ProxyConfig.DatabaseType.valueOf(value);
            }
        }
    }
```
While elegant and natural, this convertor interface will fail in Smallrye Config, because it expects class and initializer:
```
 Failed to start application (with profile dev): java.lang.NoSuchMethodError: ai.dynamind.dbproxy.mp.ProxyConfig$DatabaseType$Parser.<init>()
```

**Comment by dmlloyd** [comment]
What would the rules be for instantiating such a converter?  We'd either have to generate a class or else create a reflection proxy in order to realize it (because in the end we need an object instance to invoke upon, even if we use reflection).  If the class had other abstract methods, it would fail as well.

Also just a note that I believe we already implicitly convert enums, don't we?

Maybe an even more elegant option could be something like this:

```java
enum DatabaseType {
    mysql, oracle, postgres, mysql;
    public static final Converter<DatabaseType> CONFIG_CONVERTER = DatabaseType::valueOf;
```

i.e. look for a specifically named field in addition to using the annotations.

It's too bad Java doesn't have support for method handles in annotations.

**Comment by hrstoyanov** [comment]
Do you have docs reference for implicit conversion if enums?

**Comment by dmlloyd** [comment]
Enums have a `valueOf` method which accepts a `String`, so they should be covered under [automatic converters](https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/converters.asciidoc#automatic-converters).

**Comment by hrstoyanov** [comment]
Thanks, this seems to work - no need for enum converters .
