### ISSUE TITLE
feature: Dynamically update ConfigMappings in SmallRyeConfig.

### ISSUE THREAD

**Issue by naah69** [smallrye/smallrye-config#678]
the ConfigMappings in `io.smallrye.config.SmallRyeConfig`  was inited in `io.smallrye.config.ConfigMappingProvider#mapConfiguration(io.smallrye.config.SmallRyeConfig)`  and cached in SmallRyeConfig.

but when the ConfigSource update config in runtime，the config that was decorated by @ConfigMapping didn't update. 

is there some plan to support this feature?

I can think of two ways to do that:

1. add `ConfigMappingProvider` in `SmallRyeConfig`,manually refresh it by calling method.(It's not elegant)
2. add listener in ConfigSource.when update config,listen this operation to update ConfigMappings.

Is it feasible?

**Comment by radcortez** [comment]
I would prefer to not support this automatically. The main reason is that it may create a false expectation on the users that when a configuration changes, consumers will reload it when that is not the case. Think for instance Hibernate, it only reads the configuration at startup time and it is simply not possible to change the runtime configuration during runtime.

I understand that some user configurations may be useful to reload. While we don't support that yet, we discussed it in https://github.com/smallrye/smallrye-config/issues, by using a `Supplier`.

Would this work for you?

**Comment by UnasZole** [comment]
Hi @radcortez ,

To be honest, I don't understand how you can say that it "may create a false expectation", when the Eclipse Microprofile home page and documentation (at https://microprofile.io/microprofile-config/ ) explicitly states : 

> Under some circumstances, some data sources may change dynamically. The changed values should be fed into the client without the need for restarting the application. This requirement is particularly important for microservices running in a cloud environment. The MicroProfile Config approach allows to pick up configured values immediately after they got changed.

The values returned by ConfigSources are dynamic by definition.
I understand wanting to optimise for static configsources (to avoid complex value conversions and so on), but as a microprofile frontend, SmallRye Config should at the very least provide a way to pick up the updated values.

Can you give more details about your workaround using Supplier ?

**Comment by radcortez** [comment]
> To be honest, I don't understand how you can say that it "may create a false expectation", when the Eclipse Microprofile home page and documentation (at https://microprofile.io/microprofile-config/ ) explicitly states :

Yes, I think that MP Config made a mistake to allow such dynamic sources without additional mechanisms to handle config changes. The false expectation comes from the fact that many libraries do not reload configuration once started. I gave the example of Hibernate (or even a JDBC Datasource). If you use Config to feed such components, and later on you update the Config and change the JDBC URL, this will not be reflected in your current application datasource. This can cause some undesirable side effects. Say now for instance that you have two datasources and one initializes on application start and the other one on a job scheduler:

- Datasource one connects with the current configuration
- Configuration changes the jdbc url
- Datasource two connects with a different jdbc url
- Datasource one and two are now connected with different configurations

In Jakarta Config we discussed extensively dynamic and mutability scenarios and the only conclusion we got so far is that it should not be part of the first version of the spec. There are some ideas on how to make it work properly, but not how MP Config is doing it.

> I understand wanting to optimise for static configsources (to avoid complex value conversions and so on), but as a microprofile frontend, SmallRye Config should at the very least provide a way to pick up the updated values.

You can still get the updated values, by calling the MP Config APIs. Mappings are a SmallRye Config feature.

> Can you give more details about your workaround using Supplier ?

There is no workaround. The idea was to add `Supplier` support to force a reread of the configuration value.

I understand the frustration, and I'm sensible to open up Mappings to be more dynamic, but still with the option to lock them down if required (or the other way around). This would allow defining namespaces (like `something.jdbc.url`), locked down to the initial config, not allow reloads and have user namespace that can support dynamic configuration.

**Comment by UnasZole** [comment]
Thanks for your answer.
Indeed, I've redesigned my solution to use the MP ConfigProvider directly instead of the ConfigMapping interface, and it works, I do get a call to the ConfigSource on each request this way.
It's a bit frustrating to have to redevelop all ConfigMapping features (specifically type conversion and defaulting) on my end, but I can live with it :-) 

But if this is a known and "by design" limitation of ConfigMapping, it would have been nice to have a big bold red warning in the ConfigMapping documentation, stating that ConfigMapping only supports constant ConfigSources (ie configuration which returned values do not change depending on time or context), as it's a significant divergence from the reasonable expectations of an MP Config user.
Checking again the doc at https://smallrye.io/smallrye-config/2.12.1/config/mappings/ , unless I'm mistaken the only hint about it is the "Info" mention that "Config Mapping instances are cached" - which does not itself specify that the values returned by all getters are cached as well.
So even if your argument makes sense, such a big deviation from the underlying spec should at least be highlighted clearly - it would have saved me a fair bit of time ;-) 


Regarding your Supplier<> proposal, it would work, but it would add the inconvenience of an additional "get" call to consumers of config, which is a bit frustrating.
In addition, if you consider that a ConfigMapping will often contain config values which are part of the same config area, and loaded by the same consumer, in my opinion their "refreshability" would make more sense as a parameter of the whole ConfigMapping annotation, rather than specifying it for each individual value.

**Comment by radcortez** [comment]
> Thanks for your answer. Indeed, I've redesigned my solution to use the MP ConfigProvider directly instead of the ConfigMapping interface, and it works, I do get a call to the ConfigSource on each request this way. It's a bit frustrating to have to redevelop all ConfigMapping features (specifically type conversion and defaulting) on my end, but I can live with it :-)

Sorry about that :(

I guess that now you have that done you don't need a workaround. It is possible to "reload" mappings, by releasing and creating a new Config instance:

```java
((SmallRyeConfigProviderResolver) ConfigProviderResolver.instance()).releaseConfig(Thread.currentThread().getContextClassLoader());
SmallRyeConfig config = ConfigProvider.getConfig().unwrap(SmallRyeConfig.class);
```

Or if you don't have the `Config` associated with the current `ClassLoader` (which is done automatically when calling `ConfigProvider.getConfig()`, creating a new `SmallRyeConfig` from `SmallRyeConfigFactory` also works.

> But if this is a known and "by design" limitation of ConfigMapping, it would have been nice to have a big bold red warning in the ConfigMapping documentation, stating that ConfigMapping only supports constant ConfigSources (ie ConfigSources which returned values do not change depending on time or context), as it's a significant divergence from the reasonable expectations of an MP Config user. Checking again the doc at https://smallrye.io/smallrye-config/2.12.1/config/mappings/ , unless I'm mistaken the only hint about it is the "Info" mention that "Config Mapping instances are cached" - which does not itself specify that the values returned by all getters are cached as well. So even if your argument makes sense, such a big deviation from the underlying spec should at least be highlighted clearly - it would have saved me a fair bit of time ;-)

We can certainly improve the docs and make it more visible.

> Regarding your Supplier<> proposal, it would work, but it would add the inconvenience of an additional "get" call to consumers of config, which is a bit frustrating. In addition, if you consider that a ConfigMapping will often contain config values which are part of the same config area, and loaded by the same consumer, in my opinion their "refreshability" would make more sense as a parameter of the whole ConfigMapping annotation, rather than specifying it for each individual value.

Yes, correct.

I think that this shouldn't be done at the mapping level, but at the namespace level. There is not much point to have the mapping locked on a configuration when you can programmatically get an updated value. For instance, in Quarkus, we definitely don't want the Quarkus configuration to be reloadable, because in most cases it won't work, or requires a server restart anyway. In this case, I would probably want to lock the `quarkus` namespace and ignore any updates, no matter which API you use to retrieve them. This could allow users to have their own namespace to either be locked to updates or dynamic depending on the sources.

**Comment by radcortez** [comment]
BTW, I came up with a trick to reload a mapping :)

Check https://github.com/smallrye/smallrye-config/commit/636bc3be402efdd276352312deea7aabc85543bd
