### ISSUE TITLE
Using environment variables as indexed properties does not work as expected

### ISSUE THREAD

**Issue by michaelgarde** [smallrye/smallrye-config#697]
Hi

In my Quarkus application I'm using indexed properties to define a collection of external systems, which has worked great while the properties was defined in my application.properties file. However, once i wish to define them as environment variables (for use with ConfigMaps on Openshift) i run into issues similar to [this question on Stackoverflow](https://stackoverflow.com/questions/68862008/how-to-convert-a-collection-in-config-to-environment-variable-in-microprofile-qu). Sadly, the solution described did not work for me.

This is my (simplified) config code:
```java
@ConfigMapping(prefix = "receivingsystems")
public interface ReceivingSystemsConfig {

    List<Config> config();

    interface Config {
        String name();
        String host();
        String port();
    }
}
```

and here is an digest of my application.properties

```properties
receivingsystems.config[0].name=System 1
receivingsystems.config[0].host=127.0.0.1
receivingsystems.config[0].port=2359
receivingsystems.config[1].name=System 2
receivingsystems.config[1].host=127.0.0.1
receivingsystems.config[1].port=2369
```

which works as expected but when i attempt to convert them to environment variables as described in the [Microprofile Environment Variables Mapping Rules](https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configsources.asciidoc#environment-variables-mapping-rules) like this;

```
RECEIVINGSYSTEMS_CONFIG_0__NAME=System 1
RECEIVINGSYSTEMS_CONFIG_0__HOST=127.0.0.1
RECEIVINGSYSTEMS_CONFIG_0__PORT=2359
RECEIVINGSYSTEMS_CONFIG_1__NAME=System 2
RECEIVINGSYSTEMS_CONFIG_1__HOST=127.0.0.1
RECEIVINGSYSTEMS_CONFIG_1__PORT=2360
```

my ReceivingSystemsConfig is just empty. I feel like might have missed something obvious, since it apparently should work, so any help is appreciated.

**Comment by radcortez** [comment]
It doesn't work. It is actually documented in the Quarkus guide:
https://quarkus.io/guides/config-reference#indexed-properties

The issue here is the precision lost between a regular property and environment variable. Most terminals only accept [azAZ09_], so we cannot really represent the square brackets properly.

We did add some additional rules like for instance, a double `_` represents a `."` for properties that need to be quoted. To support indexed properties at the env variable level, we would need to define a new representation that we could map between both worlds. Considering the limitations and implications, I think we should not introduce more complexity.

My recommendation is to just set an external configuration file and point to it via `smallrye.config.locations` (or `quarkus.config.locations`), to load additional configuration properties. Would that work for you?

**Comment by michaelgarde** [comment]
Hi Roberto

Thanks for clearing this up.

> It is actually documented in the Quarkus guide:

You're right. I've read that doc but I obviously have missed that remark:

> Indexed Properties are not supported in Environment Variables.

> I think we should not introduce more complexity

Although collections being unsupported is a bit of an annoyance for us, I tend to agree that introducing a syntax for formulating support for collections in environment variables would feel very domain specific and probably not very intuitive.

> My recommendation is to just set an external configuration file and point to it via smallrye.config.locations (or quarkus.config.locations), to load additional configuration properties. Would that work for you?

Although i do suspect, in an Openshift/ConfigMap context, this would also not be very intuitive, I will look into it. We might entirely change the strategy for how these external systems are configured. Either way it won't be as simplified as I would have hoped for.

**Comment by radcortez** [comment]
Let me know if I can help with something. If you come up with some ideas, we can certainly look into them.
