### ISSUE TITLE
EnvConfigSource copy of System.getenv Map can cause issues for use of CRIU restore

### ISSUE THREAD

**Issue by tjwatson** [smallrye/smallrye-config#761]
This relates to changes from #515

We have been investigating the use of CRIU on Linux (https://criu.org/) to allow a MicroProfile Config implementation to restore an application instance using a `criu restore` operation against the Java process.  With restore we want to be able to reflect the environment the process is being restored in through the config in MicroProfile Config.  With the help of the JVM (https://github.com/eclipse-openj9/openj9/issues/13545) we are able to add new keys to the system env Map on the restore side.

The problem we see with smallrye config is that this updated system.env map is not being reflected back to the `EnvConfigSource` on the restore side.  Reverting back to using the Map directly with `System::getenv` solves the problem but likely is not something we can do because that potentially leaks back out the ProcessEnvironment.  It would be nice if a copy could only be done specifically on Graal instead of across all Java implementations.  I've done similar things to detect graal in https://github.com/apache/felix-atomos with system properties like `org.graalvm.nativeimage.kind`.  Perhaps something like that can be done here.

**Comment by dmlloyd** [comment]
Hi @tjwatson!

The challenge here is that we don't actually (overtly) support mutability of configuration in SmallRye Config (though if it happens due to the implementation specifics of a given `ConfigSource`, we "look the other way"). So the snapshot behavior is "correct" insofar as we haven't yet been brave enough to specify otherwise.

The mutability question was debated (fairly extensively) within the Jakarta Config working group over the past couple of months, and the consensus for *that* specification seems to be that mutability would only be supported by the spec (if at all) as snapshots, rather than as a quietly mutating `Config`; when a mutation is detected, an entirely new `Config` would be produced. But that project is still greatly in flux so you can safely take that with a large grain of salt.

To give a more concrete example, the experimental config mapper which is currently in `main` relies on acquiring a complete configuration and mapping all of its properties for correct operation. This is necessary in order to detect extra or misspelled property names within the mapped namespace. As a consequence, the configuration produced is inherently immutable (though it could in theory be regenerated completely). This behavior is necessary in order to ensure that only valid configurations are produced.

The reason the mapper has this behavior is twofold: first, this is equivalent to how Quarkus behaves, and this was a major inspiration for the design of the feature; and second, this is similar to what is being proposed within the Jakarta Config working group for configuration-object mapping.

So I guess all of this is to say that in terms of answering this question, we're still firmly on square one, unfortunately. But as a practical matter, maybe there is some way we can configure whether or not the environment should be copied versus being queried anew for each request?

**Comment by tjwatson** [comment]
Hi @dmlloyd (we meet again).  I understand what you say.  I came up with a PR that should work without any need for configuration.  I did not do any performance analysis on it.  I am sure it has some penalty on performance of env lookups, but I tried to limit the penalty a bit by overriding the get method on the abstract map that is used to avoid leaking ProcesseEnvironment.

So while we don't support dynamic changes of configuration explicitly, this change at least allows late binding of config lookups to happen against the latest values in the environment which would help in the CRIU/CRaC type scenarios.

**Comment by tjwatson** [comment]
It has been pointed out to me that `EnvConfigSource` has a public constructor that takes a map.   So our implementation of `io.smallrye.config.SmallRyeConfigBuilder` can easily override this behavior with something like this:

```java
    @Override
    protected List<ConfigSource> getDefaultSources() {
        List<ConfigSource> defaultSources = super.getDefaultSources();

        for (ListIterator<ConfigSource> iSources = defaultSources.listIterator(); iSources.hasNext();) {
            ConfigSource source = iSources.next();
            if (source instanceof EnvConfigSource) {
                iSources.set(new EnvConfigSource(doPrivileged((PrivilegedAction<Map<String, String>>) System::getenv), source.getOrdinal()));
            }
        }
        return defaultSources;
    }
```

**Comment by radcortez** [comment]
In this case, I think we can close this one, plus the PR.
