### ISSUE TITLE
Map Converter cannot resolve complex ENV var

### ISSUE THREAD

**Issue by svenhaag** [smallrye/smallrye-config#806]
I tried to set env var as follows:
`TEST_LANGUAGE_DE-ETR=Einfache Sprache`
and got the following error:
`java.util.NoSuchElementException: SRCFG00014: The config property test.language.de-etr#value is required but it could not be found in any config source`
at injection point:

```
@Inject
@ConfigProperty(name = "test.language")
private Optional<Map<String, String>> testLanguages;
```

Furthermore, setting ENV `TEST_LANGUAGE_DE_ETR=Einfache Sprache` does not yield an entry in the map at all.

**Comment by radcortez** [comment]
Interesting, in which system how you setting such env var? Most terminals do not accept `-` in the env name.

The issue here is the double conversion rules between properties and env vars. We generate dotted versions of the environment variables for the dynamic keys lookups to avoid double searching the dots or underscores: https://smallrye.io/smallrye-config/Main/config/environment-variables/

But we are not expecting a dash in the env variable, so when converting `test.language.de-etr` back, we get `TEST_LANGUAGE_DE_ETR` which does not exist.

If you use `TEST_LANGUAGE_DE_ETR` instead, the dotted version is `test.language.de.etr` and the Map converter will just ignore it because it only expects a single dotted key and we get `de.etr`.

Ideally, you should use `TEST_LANGUAGE__DE_ETR__`, which quotes the key, but it seems there is a bug that generated an ending dot in the property version. Let me look into that.

Anyway, I don't think we are able to support environments names with dashes for dynamic properties.

**Comment by radcortez** [comment]
I've fixed the quoted key issue that I've found.

Anyway, my recommendation is to just set the correct key format `test.language.de-etr` in a low ordinal source and then override it with`TEST_LANGUAGE_DE_ETR`. This will skip the dotted property generation, and match the format used in the environment name. This already works, so you don't need a new version.
