### ISSUE TITLE
Can colon be part of a quoted key segment ?

### ISSUE THREAD

**Issue by scrocquesel** [smallrye/smallrye-config#884]
Hi,

I'm trying to get a key that look like `quarkus.generate-code.grpc.scan-for-proto-exclude."io.quarkus:quarkus-integration-test-external-proto"` from an application.properties  but it does not work with `config.getOptionalValue`.

Retrieving all keys shows that the key name is split at the colon. I know that in application.properties key value separator can be `=` or `:`. Should quoted string protect the colon ?

AFAIK, config is built by https://github.com/quarkusio/quarkus/blob/996f3ad4a87434e492a01583fc0df702a74350a2/core/deployment/src/main/java/io/quarkus/deployment/CodeGenerator.java#L182

**Comment by radcortez** [comment]
This is because of the rules of how a properties file is loaded and parsed:
https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/Properties.html#load(java.io.Reader)

> The key contains all of the characters in the line starting with the first non-white space character and up to, but not including, the first unescaped '=', ':', or white space character other than a line terminator. All of these key termination characters may be included in the key by escaping them with a preceding backslash character; for example,

So you need to escape the key colon like this:
`quarkus.generate-code.grpc.scan-for-proto-exclude."io.quarkus\:quarkus-integration-test-external-proto"`

This works.
